name: release-artifacts
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v1.2.3)"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Prepare frontend
        run: |
          cd frontend
          npm ci

      - name: Test frontend
        run: |
          cd frontend
          npm run typescript-check

      - name: Build frontend
        run: |
          cd frontend
          npm run build 

      - name: Setup backend
        run: |
          cd backend
          mkdir -p public
          cp -r ../frontend/dist/* public/
          npm ci

      - name: Generate Riot API types
        run: |
          cd backend
          npm run generate

      - name: Run backend tests
        run: |
          cd backend
          npm run test

      - name: Build  backend
        run: |
          cd backend
          npm run build

      - name: Upload backend bundle
        uses: actions/upload-artifact@v4
        with:
          name: backend-bundle
          path: |
            backend/dist
            backend/package.json
            backend/package-lock.json

      - name: Upload Changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: |
            CHANGELOG.md
  

  package-windows:
    runs-on: windows-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-bundle
          path: backend

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: |
          cd backend
          npm ci
          npm run package

      - uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: backend/binaries

  release:
    runs-on: ubuntu-latest
    needs: [package-windows, build]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: windows-binary
          path: windows

      - uses: actions/download-artifact@v4
        with:
          name: changelog
          path: changelog

      - name: Prepare release assets
        run: |
          mkdir release
          cp windows/*.exe release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body_path: ${{ github.workspace }}/changelog/CHANGELOG.md
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}